### ISSUE TITLE
Rastrigin funcion example doesn't work

### ISSUE THREAD

**Issue by krzysztofarendt** [krzysztofarendt/modestga#22]
```
krza@DESKTOP-3738N1E:~/code/modestga$ python modestga/examples/min_rastrigin_fun.py
Traceback (most recent call last):
  File "modestga/examples/min_rastrigin_fun.py", line 37, in <module>
    res = minimize(fun, bounds, args=args, callback=callback, options=options)
  File "/home/krza/code/modestga/modestga/ga.py", line 171, in minimize
    pop = population.Population(opts['pop_size'], bounds, fun, args=args, evaluate=True)
  File "/home/krza/code/modestga/modestga/population.py", line 28, in __init__
    val=val
  File "/home/krza/code/modestga/modestga/individual.py", line 51, in __init__
    self.val = self.evaluate()
  File "/home/krza/code/modestga/modestga/individual.py", line 68, in evaluate
    self.val = self.fun(self.get_estimates(), *self.args)
TypeError: rastrigin() takes 1 positional argument but 3 were given
```

**Comment by krzysztofarendt** [comment]
Fixed: https://github.com/krzysztofarendt/modestga/pull/23
