### ISSUE TITLE
Argument passing fails with workers > 1

### ISSUE THREAD

**Issue by krzysztofarendt** [krzysztofarendt/modestga#26]
Failing test:
```
======================================================================
ERROR: test_args_passing_2workers (__main__.TestModestga)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "modestga/test/test.py", line 209, in test_args_passing_2workers
    workers=2)
  File "/home/krza/code/modestga/modestga/ga.py", line 258, in minimize
    data_from.append(pipes[i].recv())
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError

----------------------------------------------------------------------
```

**Comment by krzysztofarendt** [comment]
Fixed
